"""Writes a source's content branch: pages, categories.json, README.md, LICENSE.

ui-apt-mirror imports every .md file except README.md, takes the first
"# Heading" as the title and reads categories.json as
{"Category": ["file.md", ...]}.
"""

import json
import os
import re


def safe_filename(title, max_len=120):
    """The page file name: readable, but safe in URLs and on every filesystem."""
    name = re.sub(r"[^\w\s,()'&.+-]", " ", title, flags=re.UNICODE)
    name = re.sub(r"\s+", " ", name).strip(" .")
    return name[:max_len].rstrip() + ".md"


class Output:
    def __init__(self, out_dir, source):
        self.dir = out_dir
        self.source = source
        self.categories = {}
        self.files = set()
        os.makedirs(out_dir, exist_ok=True)

    def page(self, title, markdown, categories=()):
        """Write one page; returns its file name, or None for a duplicate title."""
        fname = safe_filename(title)
        if fname.lower() in self.files:
            return None
        self.files.add(fname.lower())
        with open(os.path.join(self.dir, fname), "w", encoding="utf-8") as f:
            f.write(markdown.rstrip() + "\n")
        for c in categories or ["General"]:
            self.categories.setdefault(c, []).append(fname)
        return fname

    def finish(self, snapshot):
        """categories.json, README.md (attribution) and LICENSE."""
        s = self.source
        cats = {k: sorted(v) for k, v in sorted(self.categories.items())}
        with open(os.path.join(self.dir, "categories.json"), "w", encoding="utf-8") as f:
            json.dump(cats, f, indent=2, ensure_ascii=False)
        with open(os.path.join(self.dir, "README.md"), "w", encoding="utf-8") as f:
            f.write(
                f"# {s['title']}\n\n"
                f"{len(self.files)} pages, {len(cats)} categories. Snapshot: {snapshot}.\n\n"
                f"Source: {s['source_url']}\n\n"
                f"{s['attribution']}\n\n"
                f"Generated by `build.py {s['id']}` on the main branch of "
                "https://github.com/Denrox/offline-library. Do not edit this branch by hand.\n"
            )
        with open(os.path.join(self.dir, "LICENSE"), "w", encoding="utf-8") as f:
            f.write(f"{s['license']}\n\n{s['attribution']}\n")
        return {"pages": len(self.files), "categories": len(cats)}
